// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260512181721_InitialCreateData")]
    partial class InitialCreateData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Core.Entities.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Core.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("CartId", "ProductId");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("c1a2b3c4-d5e6-4f70-8901-234567890abc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = new Guid("d2b3c4d5-e6f7-4a80-9012-345678901bcd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = new Guid("e3c4d5e6-f7a8-4b90-0123-456789012cde"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("Core.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("1a2b3c4d-5e6f-4a70-8901-abcdef123456"),
                            OrderDate = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = 4,
                            TotalPrice = 724.98m,
                            UserId = "a1b2c3d4-e5f6-4a70-8901-000000000001"
                        },
                        new
                        {
                            OrderId = new Guid("2b3c4d5e-6f7a-4b80-9012-bcdef1234567"),
                            OrderDate = new DateTime(2025, 3, 20, 14, 45, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalPrice = 1389.98m,
                            UserId = "a1b2c3d4-e5f6-4a70-8901-000000000001"
                        },
                        new
                        {
                            OrderId = new Guid("3c4d5e6f-7a8b-4c90-0123-cdef12345678"),
                            OrderDate = new DateTime(2025, 2, 10, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = 4,
                            TotalPrice = 114.98m,
                            UserId = "b2c3d4e5-f6a7-4b80-9012-000000000002"
                        },
                        new
                        {
                            OrderId = new Guid("4d5e6f7a-8b9c-4d01-1234-def123456789"),
                            OrderDate = new DateTime(2025, 5, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            TotalPrice = 49.99m,
                            UserId = "b2c3d4e5-f6a7-4b80-9012-000000000002"
                        });
                });

            modelBuilder.Entity("Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);

                    b.HasData(
                        new
                        {
                            OrderItemId = new Guid("0a1b2c3d-0001-4a70-8901-000000000001"),
                            OrderId = new Guid("1a2b3c4d-5e6f-4a70-8901-abcdef123456"),
                            PriceAtPurchase = 699.99m,
                            ProductId = new Guid("a1b2c3d4-e5f6-4a70-8901-1234567890ab"),
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = new Guid("0a1b2c3d-0002-4a70-8901-000000000002"),
                            OrderId = new Guid("1a2b3c4d-5e6f-4a70-8901-abcdef123456"),
                            PriceAtPurchase = 24.99m,
                            ProductId = new Guid("c3d4e5f6-a7b8-4c90-0123-3456789012cd"),
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = new Guid("0a1b2c3d-0003-4a70-8901-000000000003"),
                            OrderId = new Guid("2b3c4d5e-6f7a-4b80-9012-bcdef1234567"),
                            PriceAtPurchase = 1299.99m,
                            ProductId = new Guid("b2c3d4e5-f6a7-4b80-9012-2345678901bc"),
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = new Guid("0a1b2c3d-0004-4a70-8901-000000000004"),
                            OrderId = new Guid("2b3c4d5e-6f7a-4b80-9012-bcdef1234567"),
                            PriceAtPurchase = 89.99m,
                            ProductId = new Guid("d4e5f6a7-b8c9-4d01-1234-4567890123de"),
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = new Guid("0a1b2c3d-0005-4a70-8901-000000000005"),
                            OrderId = new Guid("3c4d5e6f-7a8b-4c90-0123-cdef12345678"),
                            PriceAtPurchase = 24.99m,
                            ProductId = new Guid("c3d4e5f6-a7b8-4c90-0123-3456789012cd"),
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemId = new Guid("0a1b2c3d-0006-4a70-8901-000000000006"),
                            OrderId = new Guid("3c4d5e6f-7a8b-4c90-0123-cdef12345678"),
                            PriceAtPurchase = 49.99m,
                            ProductId = new Guid("e5f6a7b8-c9d0-4e12-2345-5678901234ef"),
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = new Guid("0a1b2c3d-0007-4a70-8901-000000000007"),
                            OrderId = new Guid("4d5e6f7a-8b9c-4d01-1234-def123456789"),
                            PriceAtPurchase = 49.99m,
                            ProductId = new Guid("e5f6a7b8-c9d0-4e12-2345-5678901234ef"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("afcefe3a-5b81-4e95-b06a-111111111111"),
                            OrderId = new Guid("1a2b3c4d-5e6f-4a70-8901-abcdef123456"),
                            PayDate = new DateTime(2025, 1, 15, 10, 35, 0, 0, DateTimeKind.Utc),
                            PayMethod = 0,
                            PayStatus = 1
                        },
                        new
                        {
                            PaymentId = new Guid("bfcefe3a-5b81-4e95-b06a-222222222222"),
                            OrderId = new Guid("2b3c4d5e-6f7a-4b80-9012-bcdef1234567"),
                            PayDate = new DateTime(2025, 3, 20, 14, 50, 0, 0, DateTimeKind.Utc),
                            PayMethod = 1,
                            PayStatus = 1
                        },
                        new
                        {
                            PaymentId = new Guid("cfcefe3a-5b81-4e95-b06a-333333333333"),
                            OrderId = new Guid("3c4d5e6f-7a8b-4c90-0123-cdef12345678"),
                            PayDate = new DateTime(2025, 2, 10, 9, 20, 0, 0, DateTimeKind.Utc),
                            PayMethod = 0,
                            PayStatus = 1
                        },
                        new
                        {
                            PaymentId = new Guid("dfcefe3a-5b81-4e95-b06a-444444444444"),
                            OrderId = new Guid("4d5e6f7a-8b9c-4d01-1234-def123456789"),
                            PayDate = new DateTime(2025, 5, 5, 16, 5, 0, 0, DateTimeKind.Utc),
                            PayMethod = 1,
                            PayStatus = 0
                        });
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("a1b2c3d4-e5f6-4a70-8901-1234567890ab"),
                            CategoryId = new Guid("c1a2b3c4-d5e6-4f70-8901-234567890abc"),
                            Description = "Latest smartphone with advanced features and high-resolution camera",
                            Name = "Smartphone X1",
                            Price = 699.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = new Guid("b2c3d4e5-f6a7-4b80-9012-2345678901bc"),
                            CategoryId = new Guid("c1a2b3c4-d5e6-4f70-8901-234567890abc"),
                            Description = "Powerful laptop for professionals with 15-inch display and long battery life",
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = new Guid("c3d4e5f6-a7b8-4c90-0123-3456789012cd"),
                            CategoryId = new Guid("d2b3c4d5-e6f7-4a80-9012-345678901bcd"),
                            Description = "Comfortable 100% cotton t-shirt available in multiple colors",
                            Name = "Cotton T-Shirt",
                            Price = 24.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = new Guid("d4e5f6a7-b8c9-4d01-1234-4567890123de"),
                            CategoryId = new Guid("d2b3c4d5-e6f7-4a80-9012-345678901bcd"),
                            Description = "Premium quality designer jeans with modern fit and style",
                            Name = "Designer Jeans",
                            Price = 89.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = new Guid("e5f6a7b8-c9d0-4e12-2345-5678901234ef"),
                            CategoryId = new Guid("e3c4d5e6-f7a8-4b90-0123-456789012cde"),
                            Description = "Comprehensive guide to C# programming from basics to advanced topics",
                            Name = "C# Programming Guide",
                            Price = 49.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("f6a7b8c9-d0e1-4f23-3456-6789012345fa"),
                            CategoryId = new Guid("e3c4d5e6-f7a8-4b90-0123-456789012cde"),
                            Description = "Complete guide to modern web development with ASP.NET Core",
                            Name = "Web Development Mastery",
                            Price = 39.99m,
                            StockQuantity = 80
                        });
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-4a70-8901-000000000001",
                            AccessFailedCount = 0,
                            Address = "123 Main Street, New York, NY 10001",
                            ConcurrencyStamp = "a0b1c2d3-e4f5-6789-abcd-ef0123456789",
                            Email = "john.doe@email.com",
                            EmailConfirmed = true,
                            FullName = "John Doe",
                            LockoutEnabled = true,
                            NormalizedEmail = "JOHN.DOE@EMAIL.COM",
                            NormalizedUserName = "JOHN.DOE@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0Z0XG0bQn1HkxNVwOMj0vFhJYz0iM6w7ZWxHsiZ0XdHj8z0YwVPqP0Km0Pz0Vz0Q==",
                            PhoneNumber = "123-456-7890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7QJZ0XG0BQN1HKXNVWOMJ0VFHJYZ0IM6W7ZWXHSIZ0XDHJ8Z0YWV",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@email.com"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-4b80-9012-000000000002",
                            AccessFailedCount = 0,
                            Address = "456 Oak Avenue, Los Angeles, CA 90001",
                            ConcurrencyStamp = "b1c2d3e4-f5a6-7890-bcde-f12345678901",
                            Email = "jane.smith@email.com",
                            EmailConfirmed = true,
                            FullName = "Jane Smith",
                            LockoutEnabled = true,
                            NormalizedEmail = "JANE.SMITH@EMAIL.COM",
                            NormalizedUserName = "JANE.SMITH@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0Z0XG0bQn1HkxNVwOMj0vFhJYz0iM6w7ZWxHsiZ0XdHj8z0YwVPqP0Km0Pz0Vz0Q==",
                            PhoneNumber = "098-765-4321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8RKZ1YH1CRP2ILYOWXPNK1VGKIZA1JN7X8AXYITJ1YEIK8A1ZXW",
                            TwoFactorEnabled = false,
                            UserName = "jane.smith@email.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Cart", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Core.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.CartItem", b =>
                {
                    b.HasOne("Core.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.Product", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Entities.Order", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Core.Entities.Payment", b =>
                {
                    b.HasOne("Core.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Core.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
