

POST   http://localhost:5276/api/products/create
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg3NzliYTdhLWIwNjUtNGVkZi04MjBhLTNhMTg5NzM2MDllZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ3ZXVyaXlld3Vyb2V3dSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IlNvc29ld3lydWl3eXdldWlOb2h0cnRAZ2FtaWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3Nzk0ODUyMjMsImlzcyI6IkFiZHVsYWxlZW0gQWxwYXRvb2wiLCJhdWQiOiJNeUV4Y2VsbGVuY2VzVXNlcnMifQ.HbpUW7UlWINchqksH5_5iCKi_Rl0tLwP-JYqjNEC9Yk 

{ 
    "Name": "Five G",
    "Description": "Powerful laptop for professionals with 15-inch display and long battery life",
    "Price": 2299.99,
    "StockQuantity": 30,
    "CategoryId": "D2B3C4D5-E6F7-4A80-9012-345678901BCD"
     }


# POST http://localhost:5276/api/users/register
# Content-Type: application/json

# { 
#     "FullName":"yttyueeeehewuhrwuh ",
#     "Email":"SosoewyruiwyweuiNohtrt@gamil.com",
#     "UserName": "weuriyewuroewu",
#     "Address":"Tokyo",
#    "PhoneNumber":"0987747477477678543234567787",
#     "Password": "74108952000000323230096385278787676",
#    "Roles":["admin"]
# }



# GET http://localhost:5276/api/products/test
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg3NzliYTdhLWIwNjUtNGVkZi04MjBhLTNhMTg5NzM2MDllZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ3ZXVyaXlld3Vyb2V3dSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IlNvc29ld3lydWl3eXdldWlOb2h0cnRAZ2FtaWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3Nzk0ODUyMjMsImlzcyI6IkFiZHVsYWxlZW0gQWxwYXRvb2wiLCJhdWQiOiJNeUV4Y2VsbGVuY2VzVXNlcnMifQ.HbpUW7UlWINchqksH5_5iCKi_Rl0tLwP-JYqjNEC9Yk 






# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZDc5MDk2LTU5ODAtNDgyOS1iZTU0LWJkMTczN2I0YzY3MSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJyb21hbjIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoicm9tYW5AZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NzkyMTg3NDAsImlzcyI6IkFiZHVsYWxlZW0gQWxwYXRvb2wiLCJhdWQiOiJNeUV4Y2VsbGVuY2VzVXNlcnMifQ.uZEp6Kw4objc8vvgd5s3sgL0Is1NWPAFpljf_LAb_h8

#  {
        
#         "name": "Sosoasi",
#         "description": "Powerful laptop for professionals with 15-inch display and long battery life",
#         "price": 2299.99,
#         "stockQuantity": 30,
#         "categoryId": "c1a2b3c4-d5e6-4f70-8901-234567890abc",
    
#     }

# {

# "UserName":"bbbbb22",
# "Password":"666666666666"


# }



   