

POST   http://localhost:5276/api/products/create
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjFjMTNjZmZhLWUwZmMtNDUzMS04NzkwLTU4MjZlMDE0Y2NkMCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJiYmJiYjIyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NzkzODI4MzksImlzcyI6IkFiZHVsYWxlZW0gQWxwYXRvb2wiLCJhdWQiOiJNeUV4Y2VsbGVuY2VzVXNlcnMifQ.3cpq4P6NdnmvdVteZ9A7nYbNg554_z0AOQhgMwEtdkA

{ 
    "Name": "Samasi",
    "Description": "Powerful laptop for professionals with 15-inch display and long battery life",
    "Price": 2299.99,
    "StockQuantity": 30,
    "CategoryId": "D2B3C4D5-E6F7-4A80-9012-345678901BCD"
     }


# POST http://localhost:5276/api/users/login
# Content-Type: application/json

# {
#     "UserName": "bbbbb22",
   
#     "Password": "78722887878788799"
# }











# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZDc5MDk2LTU5ODAtNDgyOS1iZTU0LWJkMTczN2I0YzY3MSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJyb21hbjIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoicm9tYW5AZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NzkyMTg3NDAsImlzcyI6IkFiZHVsYWxlZW0gQWxwYXRvb2wiLCJhdWQiOiJNeUV4Y2VsbGVuY2VzVXNlcnMifQ.uZEp6Kw4objc8vvgd5s3sgL0Is1NWPAFpljf_LAb_h8

#  {
        
#         "name": "Samasi",
#         "description": "Powerful laptop for professionals with 15-inch display and long battery life",
#         "price": 2299.99,
#         "stockQuantity": 30,
#         "categoryId": "c1a2b3c4-d5e6-4f70-8901-234567890abc",
    
#     }

# {

# "UserName":"bbbbb22",
# "Password":"666666666666"


# }



   