


# POST http://localhost:5276/api/products/create
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQzZmVkMmZhLTU5Y2QtNGZhYS1iYTgwLWExYTY4MjYwZmY1ZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ1c2VyMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IkFiZHVyYWhtYW5AZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NzkyNDA5NjQsImlzcyI6IkFiZHVsYWxlZW0gQWxwYXRvb2wiLCJhdWQiOiJNeUV4Y2VsbGVuY2VzVXNlcnMifQ.FZye6iiCWJ0-dk29BQwP-NLpwiU0ojo-pWsmaMULurc

# {
#   "name": "Samaung",
#   "description": "Nice phone",
#   "price": 100,
#   "stockQuantity": 10,
#   "categoryId": "D2B3C4D5-E6F7-4A80-9012-345678901BCD"
# }




# POST   http://localhost:5276/api/carts/0adcad45-ffe7-4157-821b-8fed21196481/items
# Content-Type: application/json

# {

# "ProductId":"5EE11F4F-DD20-4EB7-A9CC-82C6A347BAB7",
# "Quantity":"2"



# }










POST http://localhost:5276/api/orders/createAndpay/aa7caf17-d8fa-4be1-bae3-63fec87d622b
Content-Type: application/json

{
 "paymentMethod":"Wallet",
 "CardNumber":"0000005555522522",
 "CVV":"xbbxbxbbb00000xxx"

}






# {
#   "UserName":"user3",
# "Password":"1212121212"
# }

#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQzZmVkMmZhLTU5Y2QtNGZhYS1iYTgwLWExYTY4MjYwZmY1ZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ1c2VyMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IkFiZHVyYWhtYW5AZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NzkyNDA2MjQsImlzcyI6IkFiZHVsYWxlZW0gQWxwYXRvb2wiLCJhdWQiOiJNeUV4Y2VsbGVuY2VzVXNlcnMifQ.rqEFmWrFQoEuAQn329h48-Zex6b944ay0DOPVoqHHgg


















# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZDc5MDk2LTU5ODAtNDgyOS1iZTU0LWJkMTczN2I0YzY3MSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJyb21hbjIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoicm9tYW5AZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NzkyMTg3NDAsImlzcyI6IkFiZHVsYWxlZW0gQWxwYXRvb2wiLCJhdWQiOiJNeUV4Y2VsbGVuY2VzVXNlcnMifQ.uZEp6Kw4objc8vvgd5s3sgL0Is1NWPAFpljf_LAb_h8

#  {
        
#         "name": "Samasi",
#         "description": "Powerful laptop for professionals with 15-inch display and long battery life",
#         "price": 2299.99,
#         "stockQuantity": 30,
#         "categoryId": "c1a2b3c4-d5e6-4f70-8901-234567890abc",
    
#     }

# {

# "UserName":"roman22",
# "Password":"666666666666"


# }



   